# Generated by Django 6.0.3 on 2026-03-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
