# Generated by Django 6.0.3 on 2026-03-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Obra')),
                ('construtora', models.CharField(max_length=100, verbose_name='Construtora')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Implantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.CharField(choices=[('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='Selecione o modelo', max_length=100, verbose_name='Modelo')),
                ('status', models.CharField(choices=[('equipamento_entregue', 'Equipamento Entregue'), ('aguardando_cliente', 'Aguardando Cliente'), ('pendente_fechamento', 'Pendente Fechamento'), ('envio_autorizado', 'Envio Autorizado'), ('aguardando_aprovacao', 'Aguardando Aprovação')], default='Selecione o status', max_length=100, verbose_name='Status')),
                ('ticket', models.CharField(max_length=100, verbose_name='Ticket')),
                ('base', models.BooleanField(default=False, verbose_name='Base')),
                ('webcam', models.BooleanField(default=False, verbose_name='Webcam')),
                ('ativacao', models.DateField(blank=True, null=True, verbose_name='Data da Ativação')),
                ('nfe', models.IntegerField(blank=True, null=True, verbose_name='Nota Fiscal')),
                ('informacao', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Nome da Obra')),
            ],
            options={
                'verbose_name': 'Implantação',
                'verbose_name_plural': 'Implantações',
            },
        ),
        migrations.CreateModel(
            name='ObrasAtivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.CharField(choices=[('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='Selecione o modelo', max_length=100, verbose_name='Modelo')),
                ('construtora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativas_construtora', to='obra.obra')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ativas_nome', to='obra.obra')),
            ],
            options={
                'verbose_name': 'Obra Ativa',
                'verbose_name_plural': 'Obras Ativas',
            },
        ),
        migrations.CreateModel(
            name='ObrasDesativadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desativacao', models.DateField(blank=True, null=True, verbose_name='Data da Desativação')),
                ('construtora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desativadas_construtora', to='obra.obra')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desativadas_nome', to='obra.obra')),
            ],
            options={
                'verbose_name': 'Obra Desativada',
                'verbose_name_plural': 'Obras Desativadas',
            },
        ),
        migrations.CreateModel(
            name='PorEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo da catraca')),
                ('ticket', models.CharField(max_length=100, verbose_name='Ticket')),
                ('base', models.BooleanField(default=False, verbose_name='Base')),
                ('facial', models.BooleanField(default=False, verbose_name='Facial')),
                ('webcam', models.BooleanField(default=False, verbose_name='Webcam')),
                ('ativacao', models.DateField(blank=True, null=True, verbose_name='Data da Ativação')),
                ('nfe', models.IntegerField(blank=True, null=True, verbose_name='Nota Fiscal')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra.obra', verbose_name='Nome da Obra')),
            ],
            options={
                'verbose_name': 'Por Estado',
                'verbose_name_plural': 'Por Estados',
            },
        ),
    ]
