# Generated by Django 6.0.3 on 2026-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porestado',
            name='modelo',
            field=models.CharField(choices=[('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='Selecione o modelo', max_length=100, verbose_name='Modelo'),
        ),
    ]
