# Generated by Django 6.0.3 on 2026-03-28 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0002_alter_porestado_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasdesativadas',
            name='alterado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='obrasdesativadas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='obrasdesativadas',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='implantacao',
            name='modelo',
            field=models.CharField(choices=[('', 'Selecione o modelo'), ('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='implantacao',
            name='status',
            field=models.CharField(choices=[('', 'Selecione o status'), ('equipamento_entregue', 'Equipamento Entregue'), ('aguardando_cliente', 'Aguardando Cliente'), ('pendente_fechamento', 'Pendente Fechamento'), ('envio_autorizado', 'Envio Autorizado'), ('aguardando_aprovacao', 'Aguardando Aprovação')], default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='obrasativas',
            name='modelo',
            field=models.CharField(choices=[('', 'Selecione o modelo'), ('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='porestado',
            name='modelo',
            field=models.CharField(choices=[('', 'Selecione o modelo'), ('digicon/controlid', 'Digicon/Controlid'), ('controlid', 'Controlid'), ('digicon', 'Digicon')], default='', max_length=100, verbose_name='Modelo'),
        ),
    ]
