# Generated by Django 6.0.3 on 2026-03-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0003_obrasdesativadas_alterado_obrasdesativadas_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasativas',
            name='construtora',
        ),
        migrations.RemoveField(
            model_name='obrasdesativadas',
            name='construtora',
        ),
        migrations.AlterField(
            model_name='obrasativas',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ativas_nome', to='obra.obra'),
        ),
        migrations.AlterField(
            model_name='obrasdesativadas',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desativadas_nome', to='obra.obra'),
        ),
    ]
