# Generated by Django 6.0.1 on 2026-03-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='modificado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função'),
        ),
    ]
