# Generated by Django 6.0.1 on 2026-03-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_pessoa_ativo_remove_pessoa_criado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Atrasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atraso', models.DateField(verbose_name='Data do Atraso')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='CustoParceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_tecnica', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Hora Técnica')),
                ('hora_adcional', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Hora Adicional')),
                ('remanejamento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Remanejamento')),
                ('instalacao_1_catraca', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Instalação de 01 Catraca')),
                ('instalacao_2_catracas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Instalação de 02 Catracas')),
                ('desmobilizacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Desmobilização')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_falta', models.DateField(verbose_name='Data da Falta')),
                ('justificada', models.BooleanField(default=False, verbose_name='Justificada')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissão', models.DateField(verbose_name='Data de Admissão')),
                ('data_limite', models.DateField(verbose_name='Data de Fim')),
                ('periodo_aquisitivo', models.DateField(verbose_name='Período Aquisitivo')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='prestador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.prestador'),
        ),
    ]
