# Generated by Django 6.0.3 on 2026-03-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_prestador_atrasos_custoparceiros_faltas_ferias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrasos',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário do Atraso'),
        ),
        migrations.AddField(
            model_name='atrasos',
            name='justificado',
            field=models.BooleanField(default=False, verbose_name='Justificado'),
        ),
    ]
