# Generated by Django 6.0.1 on 2026-03-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_atrasos_horario_atrasos_justificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferias',
            old_name='data_admissão',
            new_name='data_admissao',
        ),
    ]
