# Generated by Django 6.0.1 on 2026-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_rename_data_admissão_ferias_data_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='fim_aquisitivo',
            field=models.DateField(blank=True, null=True, verbose_name='Fim Aquisitivo'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='fim_gozo',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Gozo'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='inicio_gozo',
            field=models.DateField(blank=True, null=True, verbose_name='Início do Gozo'),
        ),
        migrations.AddField(
            model_name='ferias',
            name='limite_gozo',
            field=models.DateField(blank=True, null=True, verbose_name='Limite para Gozo'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento das Férias'),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='periodo_aquisitivo',
            field=models.DateField(blank=True, null=True, verbose_name='Início Aquisitivo'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nome',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
