# Generated by Django 6.0.1 on 2026-03-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_ferias_fim_aquisitivo_ferias_fim_gozo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_admissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
    ]
